### ISSUE TITLE
graphql-js already has a shorthand parser

### ISSUE THREAD

**Issue by helfer** [cameronhunter/graphql-shorthand-parser#10]
See this issue thread here and the code referenced in the pull request: https://github.com/graphql/graphql-js/issues/114

The GraphQL parser (for the query language) can indeed parse shorthand schema and output an AST. I wonder if it makes sense to continue this as a separate project. Or am I missing something?

**Comment by cameronhunter** [comment]
My intention with this project was to be able to parse graphql by defining it as a language rather writing a parser. I simply liked that the grammar approach was declarative and I was experimenting with both graphql and PEGjs at the time.

I personally don't have a use-case for this library but I hope that it can provide use to someone, and if nothing else I hope it's a learning aid.

If you find that graphql's parser fits your needs then I recommend using it over this.
